# Generated by Django 5.0.3 on 2024-03-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0005_subject_studentmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMarks',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
