# Generated by Django 5.0.3 on 2024-03-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0006_delete_studentmarks_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
